"""initial_schema

Revision ID: 28bf5e70081c
Revises: 
Create Date: 2026-03-23 01:42:49.308394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '28bf5e70081c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('blocked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_emails_email'), 'blocked_emails', ['email'], unique=True)
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('traceback', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_logs_timestamp'), 'error_logs', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('encrypted_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('email_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), server_default='1', nullable=False),
    sa.Column('advance_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_preferences_user_id'), 'email_preferences', ['user_id'], unique=True)
    op.create_table('grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('shares', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('vest_start', sa.Date(), nullable=False),
    sa.Column('periods', sa.Integer(), nullable=False),
    sa.Column('exercise_date', sa.Date(), nullable=False),
    sa.Column('dp_shares', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grants_user_id'), 'grants', ['user_id'], unique=False)
    op.create_table('import_backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('data_json', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_backups_created_at'), 'import_backups', ['created_at'], unique=False)
    op.create_index(op.f('ix_import_backups_user_id'), 'import_backups', ['user_id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grant_year', sa.Integer(), nullable=False),
    sa.Column('grant_type', sa.String(), nullable=False),
    sa.Column('loan_type', sa.String(), nullable=False),
    sa.Column('loan_year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('interest_rate', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('loan_number', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_user_id'), 'loans', ['user_id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_user_id'), 'prices', ['user_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('tax_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('federal_income_rate', sa.String(), nullable=False),
    sa.Column('federal_lt_cg_rate', sa.String(), nullable=False),
    sa.Column('federal_st_cg_rate', sa.String(), nullable=False),
    sa.Column('niit_rate', sa.String(), nullable=False),
    sa.Column('state_income_rate', sa.String(), nullable=False),
    sa.Column('state_lt_cg_rate', sa.String(), nullable=False),
    sa.Column('state_st_cg_rate', sa.String(), nullable=False),
    sa.Column('lt_holding_days', sa.Integer(), nullable=False),
    sa.Column('lot_selection_method', sa.String(), nullable=False),
    sa.Column('prefer_stock_dp', sa.Integer(), nullable=False),
    sa.Column('dp_min_percent', sa.Float(), nullable=False),
    sa.Column('dp_min_cap', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_settings_user_id'), 'tax_settings', ['user_id'], unique=True)
    op.create_table('loan_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_payments_loan_id'), 'loan_payments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_loan_payments_user_id'), 'loan_payments', ['user_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('price_per_share', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('federal_income_rate', sa.String(), nullable=True),
    sa.Column('federal_lt_cg_rate', sa.String(), nullable=True),
    sa.Column('federal_st_cg_rate', sa.String(), nullable=True),
    sa.Column('niit_rate', sa.String(), nullable=True),
    sa.Column('state_income_rate', sa.String(), nullable=True),
    sa.Column('state_lt_cg_rate', sa.String(), nullable=True),
    sa.Column('state_st_cg_rate', sa.String(), nullable=True),
    sa.Column('lt_holding_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_loan_id'), 'sales', ['loan_id'], unique=False)
    op.create_index(op.f('ix_sales_user_id'), 'sales', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_user_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_loan_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_loan_payments_user_id'), table_name='loan_payments')
    op.drop_index(op.f('ix_loan_payments_loan_id'), table_name='loan_payments')
    op.drop_table('loan_payments')
    op.drop_index(op.f('ix_tax_settings_user_id'), table_name='tax_settings')
    op.drop_table('tax_settings')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_prices_user_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_loans_user_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_import_backups_user_id'), table_name='import_backups')
    op.drop_index(op.f('ix_import_backups_created_at'), table_name='import_backups')
    op.drop_table('import_backups')
    op.drop_index(op.f('ix_grants_user_id'), table_name='grants')
    op.drop_table('grants')
    op.drop_index(op.f('ix_email_preferences_user_id'), table_name='email_preferences')
    op.drop_table('email_preferences')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_error_logs_timestamp'), table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_blocked_emails_email'), table_name='blocked_emails')
    op.drop_table('blocked_emails')
    # ### end Alembic commands ###
